In [ ]:
import sys
sys.path.insert(0, '..')

from oasis_dla import *

In [ ]:
# import scipy as sp
import numpy as np
import scipy.stats as stats
import scipy.linalg as la
# import matplotlib.pyplot as plt

import tensorly as tl

Get $SL(2, \mathbb{C})$

In [ ]:
# generators from sl2 lie algebra

e = np.array([
    [0, 1],
    [0, 0]
])
f = np.array([
    [0, 0],
    [1, 0]
])
h = np.array([
    [1, 0],
    [0, -1]
])

# some SL2

# A in SL_2
def form_sl2(α, β, γ):
    return la.expm(α * + e + β * f + γ * h) 

# get vector in W orbit
W = W.reshape((2, 2, 2))
W

array([[[0.        , 1.73205081],
        [1.73205081, 0.        ]],

       [[1.73205081, 0.        ],
        [0.        , 0.        ]]])

modal product W with $SL_2$

In [ ]:
tl.tenalg.multi_mode_dot(W, [A, B, C], modes=[0, 1, 2])

array([[[89.42490262, 40.64447815],
        [40.64447815, 18.05135867]],

       [[40.64447815, 18.05135867],
        [18.05135867,  7.87892572]]])

In [ ]:
modal_prod = tl.tenalg.multi_mode_dot(W, [A], modes=[0, 1, 2])
modal_prod

array([[[89.42490262, 40.64447815],
        [40.64447815, 18.05135867]],

       [[40.64447815, 18.05135867],
        [18.05135867,  7.87892572]]])

In [ ]:
tucker_decomp = tl.decomposition.tucker(modal_prod, 2)
core_tensor, factors = tucker_decomp#.core, tucker_decomp.factors

core_tensor

/mnt/c/Users/shlok/Desktop/oasis/.venv/lib/python3.12/site-packages/tensorly/tucker_tensor.py:432: RuntimeWarning: Given only one int for 'rank' for decomposition a tensor of order 3. Using this rank for all modes.
  warnings.warn(message, RuntimeWarning)


array([[[ 1.18287633e+02,  1.26199966e-04],
        [ 1.26199966e-04, -3.65345598e-01]],

       [[ 1.26199966e-04, -3.65345598e-01],
        [-3.65345598e-01,  4.06072556e-02]]])