In [13]:
import sys
sys.path.insert(0, '..')

from oasis_dla import *

In [14]:
# import scipy as sp
import numpy as np
import scipy.stats as stats
import scipy.linalg as la
# import matplotlib.pyplot as plt

import tensorly as tl

Get $SL(2, \mathbb{C})$

In [15]:
# generators from sl2 lie algebra

e = np.array([
    [0, 1],
    [0, 0]
])
f = np.array([
    [0, 0],
    [1, 0]
])
h = np.array([
    [1, 0],
    [0, -1]
])

# some SL2

# A in SL_2
def form_sl2(α, β, γ):
    return la.expm(α * + e + β * f + γ * h) 

# get vector in W orbit
W = W.reshape((2, 2, 2))
W

array([[[0.        , 1.73205081],
        [1.73205081, 0.        ]],

       [[1.73205081, 0.        ],
        [0.        , 0.        ]]])

modal product W with $SL_2$

In [16]:
A = form_sl2(1, 0, 0)
B = form_sl2(0, 1, 0)
C = form_sl2(0, 0, 1)

In [17]:
tl.tenalg.multi_mode_dot(W, [A, B, C], modes=[0, 1, 2])

array([[[4.70820224, 0.63718588],
        [9.41640447, 0.63718588]],

       [[4.70820224, 0.        ],
        [4.70820224, 0.        ]]])

In [18]:
modal_prod = tl.tenalg.multi_mode_dot(W, [A], modes=[0, 1, 2])
modal_prod

array([[[1.73205081, 1.73205081],
        [1.73205081, 0.        ]],

       [[1.73205081, 0.        ],
        [0.        , 0.        ]]])

In [19]:
tucker_decomp = tl.decomposition.tucker(modal_prod, 2)
core_tensor, factors = tucker_decomp#.core, tucker_decomp.factors

core_tensor

/mnt/c/Users/shlok/Desktop/oasis/.venv/lib/python3.12/site-packages/tensorly/tucker_tensor.py:432: RuntimeWarning: Given only one int for 'rank' for decomposition a tensor of order 3. Using this rank for all modes.
  warnings.warn(message, RuntimeWarning)


array([[[ 3.06313658,  0.33141357],
        [ 0.33141357, -0.80010315]],

       [[ 0.33141357, -0.80010315],
        [-0.80010315,  0.60596557]]])

In [ ]:
modal_prod = tl.tenalg.multi_mode_dot(W, [B], modes=[0, 1, 2])
modal_prod

tucker_decomp = tl.decomposition.tucker(modal_prod, 2)
core_tensor, factors = tucker_decomp#.core, tucker_decomp.factors

core_tensor

In [ ]:
modal_prod = tl.tenalg.multi_mode_dot(W, [C], modes=[0, 1, 2])
modal_prod

tucker_decomp = tl.decomposition.tucker(modal_prod, 2)
core_tensor, factors = tucker_decomp#.core, tucker_decomp.factors

core_tensor