In [3]:
import sys
sys.path.insert(0, '..')

from oasis_dla import *

In [4]:
import scipy as sp
import numpy as np
import sympy as smp
import scipy.stats as stats
import matplotlib.pyplot as plt


In [7]:
A = stats.unitary_group.rvs(2)
B = stats.unitary_group.rvs(2)

A, B

(array([[-0.7143906 +0.39872988j, -0.15467204-0.55383852j],
        [ 0.57499803+0.00614919j,  0.20037173-0.79321537j]]),
 array([[ 0.53305029-0.58877816j, -0.53003278-0.29709076j],
        [ 0.59650535+0.11566779j,  0.02648385+0.79378898j]]))

In [ ]:
n = 1_000
N = np.array([[n, n], [n, n]])

C = A + (1 / N) @ B
C

array([[-0.71326105+0.39825677j, -0.15517559-0.55334182j],
       [ 0.57612759+0.00567608j,  0.19986818-0.79271867j]])

In [13]:
dla, dim = compute_dla(A, C)

print(f"DLA: {dla}\nDimension: {dim}")

Iteration: 0, basis size of 2
Calculating [op[0], op[1]]
Added
[[-0.00014414-0.00083492j  0.0006583 -0.00030009j]
 [ 0.00141435-0.00232675j  0.00014414+0.00083492j]]
Iteration: 1, basis size of 3
Calculating [op[0], op[1]]
Calculating [op[0], op[2]]
Calculating [op[1], op[2]]
Added
[[-0.00188777-0.00025494j  0.00063573+0.00064123j]
 [-0.00163506-0.00477617j  0.00188777+0.00025494j]]
Iteration: 2, basis size of 4
Calculating [op[0], op[1]]
Calculating [op[0], op[2]]
Calculating [op[0], op[3]]
Calculating [op[1], op[2]]
Calculating [op[1], op[3]]
Calculating [op[2], op[3]]
DLA: [array([[-0.7143906 +0.39872988j, -0.15467204-0.55383852j],
       [ 0.57499803+0.00614919j,  0.20037173-0.79321537j]]), array([[-0.71326105+0.39825677j, -0.15517559-0.55334182j],
       [ 0.57612759+0.00567608j,  0.19986818-0.79271867j]]), array([[-0.00014414-0.00083492j,  0.0006583 -0.00030009j],
       [ 0.00141435-0.00232675j,  0.00014414+0.00083492j]]), array([[-0.00188777-0.00025494j,  0.00063573+0.00064123j