In [3]:
import sys
sys.path.insert(0, '..')

from oasis_dla import *

In [ ]:
import sys
sys.path.insert(0, '../dla_compute/build')
import cudaq  # must be imported first to initialize CUDAQ runtime
import compute_dla as oasis_dla_cpp

In [4]:
import scipy as sp
import numpy as np
import sympy as smp
import scipy.stats as stats
import matplotlib.pyplot as plt


In [5]:
A = stats.unitary_group.rvs(2)
B = stats.unitary_group.rvs(2)

A, B

(array([[ 0.46151854+0.48507117j,  0.51815331+0.5321877j ],
        [ 0.60723543+0.42775195j, -0.55177782-0.37925537j]]),
 array([[-0.31310359+0.15214281j, -0.77206578+0.53172657j],
        [-0.25331129-0.9025808j ,  0.14334322+0.31722864j]]))

In [ ]:
n = 1_000

N = lambda ε: np.array([[ε, ε], [ε, ε]])

C = lambda ε: A + (1 / ε) * B
C(n)

array([[ 0.46120544+0.48522331j,  0.51738124+0.53271943j],
       [ 0.60698212+0.42684936j, -0.55163448-0.37893814j]])

In [ ]:
dla, dim = compute_dla(A, C(1000))

print(f"DLA: {dla}\nDimension: {dim}")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1689515058.py, line 3)

In [16]:
dla, dim = compute_dla(A, C(1_000_000))

print(f"DLA: {dla}\nDimension: {dim}")

Iteration: 0, basis size of 2
Calculating [op[0], op[1]]
Added
[[ 1.04536109e-06-5.95114953e-07j -1.09326405e-06+1.99934812e-07j]
 [-7.30000022e-07+8.38033526e-07j -1.04536109e-06+5.95114952e-07j]]
Iteration: 1, basis size of 3
Calculating [op[0], op[1]]
Calculating [op[0], op[2]]
Calculating [op[1], op[2]]
Added
[[-7.48518839e-08+3.91971135e-07j -2.99734979e-06-1.23827898e-06j]
 [ 3.24272473e-06-4.66572254e-08j  7.48518839e-08-3.91971135e-07j]]
Iteration: 2, basis size of 4
Calculating [op[0], op[1]]
Calculating [op[0], op[2]]
Calculating [op[0], op[3]]
Calculating [op[1], op[2]]
Calculating [op[1], op[3]]
DLA: [array([[ 0.46151854+0.48507117j,  0.51815331+0.5321877j ],
       [ 0.60723543+0.42775195j, -0.55177782-0.37925537j]]), array([[ 0.46151823+0.48507132j,  0.51815254+0.53218823j],
       [ 0.60723518+0.42775104j, -0.55177768-0.37925505j]]), array([[ 1.04536109e-06-5.95114953e-07j, -1.09326405e-06+1.99934812e-07j],
       [-7.30000022e-07+8.38033526e-07j, -1.04536109e-06+5.95114

In [17]:
dla, dim = compute_dla(A, C(1_000_000_000))

print(f"DLA: {dla}\nDimension: {dim}")

Iteration: 0, basis size of 2
DLA: [array([[ 0.46151854+0.48507117j,  0.51815331+0.5321877j ],
       [ 0.60723543+0.42775195j, -0.55177782-0.37925537j]]), array([[ 0.46151854+0.48507117j,  0.51815331+0.5321877j ],
       [ 0.60723543+0.42775194j, -0.55177782-0.37925537j]])]
Dimension: 2
