In [19]:
import sys
sys.path.insert(0, '..')

from oasis_dla import *

In [20]:
import sys
sys.path.insert(0, '../dla_compute/build')
import cudaq  # must be imported first to initialize CUDAQ runtime
import compute_dla as oasis_dla_cpp

In [21]:
import scipy as sp
import numpy as np
import sympy as smp
import scipy.stats as stats
import matplotlib.pyplot as plt


In [22]:
A = stats.unitary_group.rvs(2)
B = stats.unitary_group.rvs(2)

A, B

(array([[ 0.65686446+0.37499071j, -0.62239258-0.20134182j],
        [ 0.35629713+0.54860131j,  0.53293544+0.53672038j]]),
 array([[ 0.41470887+0.0147574j , -0.58219792+0.69917405j],
        [ 0.45743992+0.78647791j,  0.41136206+0.05461212j]]))

In [23]:
n = 1_000

N = lambda ε: np.array([[ε, ε], [ε, ε]])

C = lambda ε: A + (1 / ε) * B
C(n)

array([[ 0.65727917+0.37500547j, -0.62297478-0.20064264j],
       [ 0.35675457+0.54938779j,  0.53334681+0.53677499j]])

In [24]:
dla, dim = compute_dla(A, C(1000))

print(f"DLA: {dla}\nDimension: {dim}")

Iteration: 0, basis size of 2
Calculating [op[0], op[1]]
Added
[[ 4.64646935e-04-5.11318960e-04j  5.10334200e-05+1.56675200e-04j]
 [-1.60830078e-04-3.58498832e-05j -4.64646935e-04+5.11318960e-04j]]
Iteration: 1, basis size of 3
Calculating [op[0], op[1]]
Calculating [op[0], op[2]]
Calculating [op[1], op[2]]
Added
[[ 0.00016065-2.91254041e-05j  0.00081595-4.38213548e-04j]
 [ 0.00091785+1.23880726e-04j -0.00016065+2.91254041e-05j]]
Iteration: 2, basis size of 4
Calculating [op[0], op[1]]
Calculating [op[0], op[2]]
Calculating [op[0], op[3]]
Calculating [op[1], op[2]]
Calculating [op[1], op[3]]
Calculating [op[2], op[3]]
DLA: [array([[ 0.65686446+0.37499071j, -0.62239258-0.20134182j],
       [ 0.35629713+0.54860131j,  0.53293544+0.53672038j]]), array([[ 0.65727917+0.37500547j, -0.62297478-0.20064264j],
       [ 0.35675457+0.54938779j,  0.53334681+0.53677499j]]), array([[ 4.64646935e-04-5.11318960e-04j,  5.10334200e-05+1.56675200e-04j],
       [-1.60830078e-04-3.58498832e-05j, -4.64646935e

In [25]:
dla, dim = compute_dla(A, C(1_000_000))

print(f"DLA: {dla}\nDimension: {dim}")

Iteration: 0, basis size of 2
Calculating [op[0], op[1]]
Added
[[ 4.64646935e-07-5.11318960e-07j  5.10334200e-08+1.56675200e-07j]
 [-1.60830078e-07-3.58498831e-08j -4.64646935e-07+5.11318960e-07j]]
Iteration: 1, basis size of 3
Calculating [op[0], op[1]]
Calculating [op[0], op[2]]
Calculating [op[1], op[2]]
Added
[[ 1.60650526e-07-2.91254042e-08j  8.15948935e-07-4.38213548e-07j]
 [ 9.17854751e-07+1.23880726e-07j -1.60650526e-07+2.91254042e-08j]]
Iteration: 2, basis size of 4
Calculating [op[0], op[1]]
Calculating [op[0], op[2]]
Calculating [op[0], op[3]]
Calculating [op[1], op[2]]
Calculating [op[1], op[3]]
DLA: [array([[ 0.65686446+0.37499071j, -0.62239258-0.20134182j],
       [ 0.35629713+0.54860131j,  0.53293544+0.53672038j]]), array([[ 0.65686487+0.37499073j, -0.62239316-0.20134112j],
       [ 0.35629759+0.5486021j ,  0.53293585+0.53672043j]]), array([[ 4.64646935e-07-5.11318960e-07j,  5.10334200e-08+1.56675200e-07j],
       [-1.60830078e-07-3.58498831e-08j, -4.64646935e-07+5.11318

In [26]:
dla, dim = compute_dla(A, C(1_000_000_000))

print(f"DLA: {dla}\nDimension: {dim}")

Iteration: 0, basis size of 2
DLA: [array([[ 0.65686446+0.37499071j, -0.62239258-0.20134182j],
       [ 0.35629713+0.54860131j,  0.53293544+0.53672038j]]), array([[ 0.65686446+0.37499071j, -0.62239258-0.20134182j],
       [ 0.35629713+0.54860131j,  0.53293544+0.53672038j]])]
Dimension: 2


In [39]:
oasis_dla_cpp.sample_bell(2, 1000)

{'00': 517, '11': 483}