In [35]:
import cudaq

import numpy as np
import scipy as sp
import scipy.stats as stats

import sympy as smp

In [2]:
def linear_indep(*mats: np.ndarray):
    vecs = [m.flatten() for m in mats]

    M = np.column_stack(vecs)
    rank = np.linalg.matrix_rank(M)
    
    return rank == len(mats)

In [14]:
X = np.array([
    [0, 1],
    [0, 0]
])

Y = np.array([
    [0, 0],
    [1, 0]
])

op_set = [X, Y]

# commutate
def commutator(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    return A @ B - B @ A

def single_pass(*ops: np.ndarray):
    op_set = [*ops]

    # single pass to calculate commutators
    for i in op_set:
        for j in op_set:
            H = commutator(i, j)
            
            # continue if 0 matrix
            if np.all(H == 0): 
                continue

            ops_curr = [m.flatten() for m in op_set]
            ops_new = ops_curr + [H.flatten()]
            rank_curr, rank_new = np.linalg.matrix_rank(ops_curr), np.linalg.matrix_rank(ops_new)

            if rank_new > rank_curr:
                op_set.append(H)

    return op_set

dla = single_pass(X, Y)
dla

[array([[0, 1],
        [0, 0]]),
 array([[0, 0],
        [1, 0]]),
 array([[ 1,  0],
        [ 0, -1]])]

In [ ]:
X_3 = np.array([
    [0, 0, 1],
    [0, 0, 0],
    [0, 0, 0]
])

Y_3 = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [1, 0, 0]
])

dla = single_pass(X_3, Y_3)

[array([[0, 0, 1],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [1, 0, 0]]),
 array([[ 1,  0,  0],
        [ 0,  0,  0],
        [ 0,  0, -1]])]

In [ ]:
X = stats.unitary_group.rvs(dim=3)
Y = stats.unitary_group.rvs(dim=3)

dla = single_pass(X, Y)
dla

Matrix([[0.0778478650212411 - 0.74590850391063*I, 0.125804183615393 + 0.0694654308039166*I, -0.448134857055812 + 0.464847528664075*I], [-0.0149897082855279 + 0.308555446796544*I, -0.791445957210831 + 0.106590296528458*I, -0.257145935244743 + 0.447991761515113*I], [0.544862249861551 + 0.212730315843671*I, 0.208209128145119 - 0.546121438661537*I, 0.241292835676665 + 0.507985277384371*I]])
Matrix([[-0.404459965396639 - 0.537610378602437*I, 0.576038054742797 - 0.412013679976403*I, 0.213189268489552 + 0.0190378573274652*I], [0.369457052172953 - 0.627178315814626*I, -0.588040801361029 - 0.321303675405939*I, 0.0969406001500646 - 0.108274331766399*I], [-0.1322401011182 + 0.00697277836613269*I, -0.20973514683538 - 0.0735392363823066*I, 0.105537496613826 + 0.960171298113436*I]])
Matrix([[-0.0845367030340095 - 0.357473866362787*I, 0.184773307478862 - 0.786848926162958*I, -0.95249704723216 - 1.07546074706316*I], [0.232521568052199 + 0.897388064475574*I, 0.15427249651028 + 0.237588549005609*I, -1.0